### PR TITLE
Add RegionInfo5 to RegionInfoMessage

### PR DESCRIPTION
**Pull request by callcolor**
Fixes "WARNING: Finished reading RegionInfoMessage but we're not at the end of the packet (154 < 183, seq 39)"

Fixes "TypeError: Cannot read properties of undefined (reading 'removeAttachment')"

Adds new Region properties.
KRA8FUK

### CODE REVIEW

**Comment by IAmNolanPerry** [comment]
@TomMettam Can you review this please whenever possible, this is a pretty good fix for it, mainly for the fixing the Reading RegionInfoMessage

**Review by Lokomojo — APPROVED** [review]

**Comment by TomMettam** [comment]
I've merged this for now, but I will be backing out the message changes since these are auto-generated from the message template.

**Comment by Lokomojo** [comment]
Done (Ignore previous comment, i misread something :P)

**Comment by Lokomojo** [comment]
Note that this currently causes issues with OpenSim which doesn't support the extended message (yet).

**Comment by IAmNolanPerry** [comment]
Is that the only thing prohibiting this from being merged? What is the solution to this other than getting OpenSimulator Core to add support for this? 
I'm thinking making it be a switch or flag maybe that changes the params based on if it's SL or something else?

**Comment by Lokomojo** [comment]
The message handler needs to be adjusted to be a bit more tolerant to missing data before I can merge this. 

@callcolor  can you please split out the ToS stuff into a different MR

**Pull request closed without merging**
